### ISSUE TITLE
能否补充训练集和训练方法吗

### ISSUE THREAD

**Issue by einsitang** [pk5ls20/sudoku#2]
你好，很不错的项目，我想了解一下你的模型的数据集、方法、训练数据，方便我学习，我正好有一个个人兴趣项目用到。

**Comment by pk5ls20** [comment]
数据集要等我找下

**Comment by einsitang** [comment]
我在尝试使用yolo8训练一个识别数独的模型，可是效果都很差，你能帮我吗？

**Comment by einsitang** [comment]
好像终于训练出一个精确度比较高的检测模型

**Comment by einsitang** [comment]
你知道在如何将yolo迁移到tf上吗，我的意思是可以在tf上使用其基本功能，不是单纯的导出模型，我这里遇到于此相关的问题，好像国内很少人涉及这种场景，反正响应的资料都比较少

这是在yolo上运行模型的效果
![20240714172027](https://github.com/user-attachments/assets/5d8d1e56-d353-465f-a118-40b1abfac8f5)


这个是迁移到tensorflow框架上的效果
<img width="878" alt="2" src="https://github.com/user-attachments/assets/49f8ffb4-b451-404b-992f-25d9368cba3f">

可以看到相同的模型下，检测的置信度差不多，可是检测框却差很远，我不清楚是我编码问题，还是模型导出转换的问题

**Comment by pk5ls20** [comment]
> 你知道在如何将yolo迁移到tf上吗，我的意思是可以在tf上使用其基本功能，不是单纯的导出模型，我这里遇到于此相关的问题，好像国内很少人涉及这种场景，反正响应的资料都比较少
> 
> 这是在yolo上运行模型的效果 ![20240714172027](https://private-user-images.githubusercontent.com/1745525/348527963-5d8d1e56-d353-465f-a118-40b1abfac8f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTg4NjEsIm5iZiI6MTcyMDk1ODU2MSwicGF0aCI6Ii8xNzQ1NTI1LzM0ODUyNzk2My01ZDhkMWU1Ni1kMzUzLTQ2NWYtYTExOC00MGIxYWJmYWM4ZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMTIwMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI1MGVkNTBmZDlhMWMwYmQ4MTk0YWQyNWU5YmFiN2Q4NTVjMTMxZWRjYzI3NzY0N2FmYWNlZDQ3NDA1MzQ4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K9r3EFCk3nnyRs78aKdLBBFkLdwuPPfLv6BVAHlDxSg)
> 
> 这个是迁移到tensorflow框架上的效果 <img alt="2" width="878" src="https://private-user-images.githubusercontent.com/1745525/348528045-49f8ffb4-b451-404b-992f-25d9368cba3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTg4NjEsIm5iZiI6MTcyMDk1ODU2MSwicGF0aCI6Ii8xNzQ1NTI1LzM0ODUyODA0NS00OWY4ZmZiNC1iNDUxLTQwNGItOTkyZi0yNWQ5MzY4Y2JhM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMTIwMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzhhOTkxNWM0MTEwM2RmY2I4YjI2NTgzMTE3ZjMzOGZiYmExMzIwZmZmZmU1NGQ2MTM5Zjc2ZGZjMmY2NjRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QPbbo4Te4ID7u5DDU3gkpo6hrDjcwk6JQm9F1I950RQ">
> 
> 可以看到相同的模型下，检测的置信度差不多，可是检测框却差很远，我不清楚是我编码问题，还是模型导出转换的问题


这个场景不太清楚，没有接触过😂

**Comment by pk5ls20** [comment]
> 你好，很不错的项目，我想了解一下你的模型的数据集、方法、训练数据，方便我学习，我正好有一个个人兴趣项目用到。

https://huggingface.co/datasets/pk5ls20/SudokuDetect
